<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.1" Condition="$(IsPackable) == 'true'"/>
    <PackageVersion Include="Microsoft.Maui.Controls" Version="10.0.1" Condition="$(IsPackable) != 'true'"/>
    <PackageVersion Include="ReactiveUI" Version="20.1.63" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="10.0.1" />
    <PackageVersion Include="Refit" Version="9.0.2" />
  </ItemGroup>

  <ItemGroup>
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.6.133" />
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>